language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - "pip install -r requirements.txt"
  - |
    if [[ `python --version 2>&1` =~ .*PyPy.* ]]; then
      pip install git+https://bitbucket.org/pypy/numpy.git
    fi

script: python test_all.py
