language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"
  - "pypy"
  #- "pypy3"  # numpy does not work with pypy3
  
install:
  - "pip install -r requirements.txt"
  - |
    # Install interpreter-specific requirements.
    if [[ `python --version 2>&1` =~ .*PyPy.* ]]; then
      pip install -r requirements_pypy.txt
    else
      pip install -r requirements_cpython.txt
    fi

script: python test_all.py
